export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE";

export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE";

export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";

export const FETCH_SINGLE_TASK_SUCCESS = "FETCH_SINGLE_TASK_SUCCESS ";
export const FETCH_SINGLE_TASK_FAILURE = "FETCH_SINGLE_TASK_FAILURE ";

export const INITIAL_LOAD_DATA_SUCCESS = "INITIAL_LOAD_DATA_SUCCESS";
export const INITIAL_LOAD_DATA_FAILURE = "INITIAL_LOAD_DATA_FAILURE";

export const STRIKE_TASK_SUCCESS = "STRIKE_TASK_SUCCESS";
export const STRIKE_TASK_FAILURE = "STRIKE_TASK_FAILURE";

export const UNDO_TASK_SUCCESS = "UNDO_TASK_SUCCESS";
export const UNDO_TASK_FAILURE = "UNDO_TASK_FAILURE";
